=== admin-shell-io/aasx-package-explorer/src/AasxToolkit/schemaV10/AAS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.admin-shell.io/aas/1/0"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:aas="http://www.admin-shell.io/aas/1/0"  xmlns:IEC61360="http://www.admin-shell.io/IEC61360/1/0">
    <import schemaLocation="IEC61360.xsd" namespace="http://www.admin-shell.io/IEC61360/1/0">
	</import>
	<element name="aasenv" type="aas:aasenv_t"></element>

	<complexType name="aasenv_t">
		<sequence>
			<element name="assetAdministrationShells" type="aas:assetAdministrationShells_t" minOccurs="0" maxOccurs="1">
			</element>
			<element name="assets" type="aas:assets_t" minOccurs="0" maxOccurs="1"></element>
			<element name="submodels" type="aas:submodels_t" minOccurs="0" maxOccurs="1"></element>
			<element name="conceptDescriptions" type="aas:conceptDescriptions_t" minOccurs="0" maxOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="assetAdministrationShells_t">
		<sequence>
			<element name="assetAdministrationShell" type="aas:assetAdministrationShell_t"
				minOccurs="0" maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>

	<complexType name="assets_t">
		<sequence>
			<element name="asset" type="aas:asset_t" minOccurs="0"
				maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>

	<complexType name="asset_t">
		<sequence>
			<group ref="aas:identifiable"></group>
			<group ref="aas:hasDataSpecifications"></group>
			<group ref="aas:hasKind"></group>
			<element name="assetIdentificationModelRef" type="aas:reference_t" minOccurs="0" maxOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="assetAdministrationShell_t">
		<sequence>
			<group ref="aas:identifiable"></group>
			<group ref="aas:hasDataSpecifications"></group>
			<element name="derivedFrom" type="aas:reference_t" minOccurs="0" maxOccurs="1"></element>
			<element name="assetRef" type="aas:reference_t" minOccurs="1" maxOccurs="1"></element>
			<element name="submodelRefs" type="aas:submodelRefs_t" minOccurs="0" maxOccurs="1"></element>
			<element name="views" type="aas:views_t" minOccurs="0" maxOccurs="1"></element>
			<element name="conceptDictionaries"
				type="aas:conceptDictionaries_t" minOccurs="0" maxOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="submodel_t">
			<sequence>
			<group ref="aas:identifiable"></group>
			<group ref="aas:hasDataSpecifications"></group>
			<group ref="aas:hasSemantics"></group>
			<group ref="aas:hasKind"></group>
			<group ref="aas:qualifiable"></group>
			<element name="submodelElements" type="aas:submodelElements_t"></element>
		</sequence>
	</complexType>

	<complexType name="conceptDescription_t">
		<sequence>
			<group ref="aas:identifiable"></group>
			<group ref="aas:hasDataSpecifications"></group>
			<element name="isCaseOf" type="aas:reference_t" maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="view_t">
		<sequence>
			<group ref="aas:referable"></group>
			<group ref="aas:hasSemantics"></group>
			<group ref="aas:hasDataSpecifications"></group>
			<element name="containedElements" type="aas:containedElements_t"></element>
		</sequence>
	</complexType>

	<complexType name="submodelElements_t">
		<sequence>
			<element name="submodelElement" type="aas:submodelElement_t" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

    <complexType name="submodelElementAbstract_t">
    		<sequence>
			<group ref="aas:referable"></group>
			<group ref="aas:hasSemantics"></group>
			<group ref="aas:hasDataSpecifications"></group>
			<group ref="aas:hasKind"></group>
			<group ref="aas:qualifiable"></group>
		</sequence>
    </complexType>

    <complexType name="submodelRefs_t">
    	<sequence>
    		<element name="submodelRef" type="aas:reference_t" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="views_t">
    	<sequence>
    		<element name="view" type="aas:view_t" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="conceptDictionary_t">
    	<sequence>
			<group ref="aas:referable"></group>
    		<element name="conceptDescriptionRefs" type="aas:conceptDescriptionsRef_t" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="conceptDescriptions_t">
    	<sequence>
    		<element name="conceptDescription" type="aas:conceptDescription_t" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="conceptDictionaries_t">
    	<sequence>
    		<element name="conceptDictionary" type="aas:conceptDictionary_t" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="submodels_t">
    	<sequence>
    		<element name="submodel" type="aas:submodel_t" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="containedElements_t">
    	<sequence>
    		<element name="containedElementRef" minOccurs="0" maxOccurs="unbounded" type="aas:reference_t"></element>
    	</sequence>
    </complexType>

    <complexType name="submodelElement_t">
    	<choice>
    		<element name="property" type="aas:property_t"></element>
    		<element name="file" type="aas:file_t"></element>
    		<element name="blob" type="aas:blob_t"></element>
    		<element name="referenceElement"
    			type="aas:referenceElement_t">
    		</element>
    		<element name="submodelElementCollection"
    			type="aas:submodelElementCollection_t">
    		</element>
    		<element name="relationshipElement"
    			type="aas:relationshipElement_t">
    		</element>
    		<element name="operation" type="aas:operation_t"></element>
    		<element name="operationVariable"
    			type="aas:operationVariable_t">
    		</element>
    		<element name="event" type="aas:event_t"></element>
    	</choice>
    </complexType>

    <complexType name="property_t">
    	<complexContent>
    		<extension base="aas:submodelElementAbstract_t">
    			<sequence>
    				<element name="valueType" type="string"></element>
    				<element name="value" type="aas:propertyValueType_t" maxOccurs="1" minOccurs="0"></element>
    				<element name="valueId" type="aas:reference_t" maxOccurs="1" minOccurs="0"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>
    
    <complexType name="file_t">
    	<complexContent>
    		<extension base="aas:submodelElementAbstract_t">
    			<sequence>
    			<element name="mimeType" type="string"></element>
    			<element name="value" type="aas:pathType_t"></element>
    			</sequence>
    		</extension>
       </complexContent>
    </complexType>

    <complexType name="blob_t">
    	<complexContent>
    		<extension base="aas:submodelElementAbstract_t">
    			<sequence>
    			<element name="mimeType" type="string"></element>
    			<element name="value" type="aas:blobType_t"></element>
    			</sequence>
    		</extension>
       </complexContent>
    </complexType>
    
    <complexType name="referenceElement_t">
    	<complexContent>
    		<extension base="aas:submodelElementAbstract_t">
    			<sequence>
    			<element name="value" type="aas:reference_t"></element>
    			</sequence>
    		</extension>
       </complexContent>
    </complexType>        

    <complexType name="submodelElementCollection_t">
    	<complexContent>
    		<extension base="aas:submodelElementAbstract_t">
    			<sequence>
    			<element name="value" type="aas:submodelElements_t"></element>
    			<element name="ordered" type="boolean"></element>
    			<element name="allowDuplicates" type="boolean"></element>
    			</sequence>
    		</extension>
       </complexContent>
    </complexType> 

    <complexType name="relationshipElement_t">
   	<complexContent>
    		<extension base="aas:submodelElementAbstract_t">
    			<sequence>
    			<element name="first" type="aas:reference_t"></element>
    			<element name="second" type="aas:reference_t"></element>
    			</sequence>
    		</extension>
       </complexContent>    
    </complexType>

    <!-- 190318: MIHO added min/maxOccurs to reflect multiplicity of the spec -->
    <complexType name="operation_t">
   	<complexContent>
    		<extension base="aas:submodelElementAbstract_t">
    			<sequence>
    			<element name="in" minOccurs="0" maxOccurs="unbounded" type="aas:operationVariable_t"></element>
    			<element name="out" minOccurs="0" maxOccurs="unbounded" type="aas:operationVariable_t"></element>
    			</sequence>
    		</extension>
       </complexContent>      
    
    </complexType>

    <complexType name="operationVariable_t">
    	<complexContent>
    		<extension base="aas:submodelElementAbstract_t">
    			<sequence>
    			<element name="value" type="aas:submodelElement_t"></element>
    			</sequence>
    		</extension>
       </complexContent>      
    </complexType>

    <complexType name="event_t">
    	<complexContent>
    		<extension base="aas:submodelElementAbstract_t">
    			<sequence>
    			</sequence>
    		</extension>
       </complexContent>      
    </complexType>

    <complexType name="dataSpecificationContent_t">
    	<choice>
	    		<element name="dataSpecificationIEC61360" type="IEC61360:dataSpecificationIEC61630_t"></element>
    	</choice>
    </complexType>

    <complexType name="conceptDescriptionsRef_t">
    	<sequence>
    		<element name="conceptDescriptionRef" type="aas:reference_t" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>



    <complexType name="pathType_t">
    	<simpleContent>
    		<extension base="string"></extension>
    	</simpleContent>
    </complexType>

    <complexType name="blobType_t">
    	<simpleContent>
    		<extension base="base64Binary"></extension>
    	</simpleContent>
    </complexType>
    
    	<complexType name="idPropertyDefinition_t">
		<simpleContent>
			<extension base="string">
				<attribute name="idType" type="string" />
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="idShort_t">
		<simpleContent>
			<extension base="string">
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="administration_t">
		<sequence>
			<element name="version" type="string" minOccurs="0"
				maxOccurs="1" />
			<element name="revision" type="string" minOccurs="0"
				maxOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="identification_t">
		<simpleContent>
	 		<extension base="string">
				<attribute name="idType" use="optional">
					<simpleType>
						<restriction base="string">
							<enumeration value="URI"></enumeration>
							<enumeration value="IRDI"></enumeration>
							<enumeration value="Custom"></enumeration>
						</restriction>
					</simpleType>
				</attribute>
			</extension>
		</simpleContent>
	</complexType>

	
	<group name="identifiable">
		<sequence>
			<group ref="aas:referable"></group>
            <element name="identification" type="aas:identification_t" minOccurs="0" maxOccurs="1"></element>
            <element name="administration" type="aas:administration_t" minOccurs="0" maxOccurs="1"></element>
		</sequence>
	</group>

	<group name="referable">
		<sequence>
			<element name="idShort" type="aas:idShort_t" minOccurs="0" maxOccurs="1"></element>
			<element name="category" type="string" minOccurs="0" maxOccurs="1"></element>
			<element name="description"
				type="aas:langStrings_t" minOccurs="0" maxOccurs="1">
			</element>
			<element name="parent" type="string" minOccurs="0" maxOccurs="1"></element>
		</sequence>
	</group>

	<complexType name="qualifiers_t">
		<sequence>
			<element name="qualifier" type="string" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

    <group name="qualifiable">
    	<sequence>
    		<element name="qualifier" type="aas:constraint_t" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    </group>

    <group name="hasDataSpecifications">
    	<sequence>
    		<element name="embeddedDataSpecification" type="aas:embeddedDataSpecification_t" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </group>

    <group name="hasSemantics">
    	<sequence>
    		<element name="semanticId" type="aas:semanticId_t" minOccurs="0"></element>
    	</sequence>
    </group>

    <complexType name="semanticId_t">
    	<complexContent>
    		<extension base="aas:reference_t"></extension>
    	</complexContent>
    </complexType>

    <complexType name="reference_t">
    	<sequence>
    		<element name="keys" type="aas:keys_t"></element>
    	</sequence>
    </complexType>

    <complexType name="qualifier_t">
    	<sequence>
    		<group ref="aas:hasSemantics"></group>
    		<element name="qualifierType" type="string"></element>
    		<element name="qualifierValue" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="qualifierValueId" type="aas:reference_t" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="formula_t">
    	<sequence>
    		<element name="dependsOn" type="aas:references_t"></element>
    	</sequence>
    </complexType>

    <complexType name="constraint_t">
    	<choice>
    		<element name="qualifier" type="aas:qualifier_t"></element>
            <element name="formula" type="aas:formula_t"></element>
        </choice>
    </complexType>

    <complexType name="references_t">
    	<sequence>
    		<element name="reference" type="aas:reference_t" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    
    <group name="hasKind">
    	<sequence>
    		<element name="kind" minOccurs="0" maxOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="Type"></enumeration>
    					<enumeration value="Instance"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    	</sequence>
    </group>

    <complexType name="keys_t">
    	<sequence>
    	 		<element ref="aas:key" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <element name="key" type="aas:key_t"></element>

    <attributeGroup name="keyTypes">
    	<attribute name="localKeyType" use="optional">
    		<simpleType>
    				<restriction base="string">
    					<enumeration value="idShort"></enumeration>
    				</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="identifierType" use="optional">
    		<simpleType>
    				<restriction base="string">
    					<enumeration value="IRDI"></enumeration>
    					<enumeration value="URI"></enumeration>
    					<enumeration value="Custom"></enumeration>
    				</restriction>
    		</simpleType>
    	</attribute>
    </attributeGroup>

    <complexType name="key_t">
    	<simpleContent>
    		<extension base="string">
        		<attribute name="type">
        			<simpleType>
		        		<restriction base="string">
		        			<enumeration value="GlobalReference"></enumeration>
		        			<enumeration value="ConceptDictionary"></enumeration>
		    				<enumeration value="AccessPermissionRule"></enumeration>
		    				<enumeration value="DataElement"></enumeration>
		    				<enumeration value="View"></enumeration>
		    				<enumeration value="Property"></enumeration>
		    				<enumeration value="SubmodelElement"></enumeration>
		    				<enumeration value="File"></enumeration>
		    				<enumeration value="Blob"></enumeration>
		    				<enumeration value="ReferenceElement"></enumeration>
		    				<enumeration value="SubmodelElementCollection"></enumeration>
		    				<enumeration value="RelationShipElement"></enumeration>
		    				<enumeration value="Event"></enumeration>
		    				<enumeration value="Operation"></enumeration>
		    				<enumeration value="OperationVariable"></enumeration>
		    				<enumeration value="AssetAdministrationShell"></enumeration>
		    				<enumeration value="Submodel"></enumeration>
		    				<enumeration value="ConceptDescription"></enumeration>
		    				<enumeration value="Asset"></enumeration>    				
		        		</restriction>
		        	</simpleType>
		        </attribute>
        
		        <attribute name="idType">
		        	<simpleType>
		        		<restriction base="string">
		    				<enumeration value="idShort"></enumeration>
		    				<enumeration value="IRDI"></enumeration>
		    				<enumeration value="URI"></enumeration>
		    				<enumeration value="Custom"></enumeration>
		    	   		</restriction>
		        	</simpleType>
		        </attribute>
		        <attribute name="local" type="boolean"></attribute>
		    </extension>
        </simpleContent>
    </complexType>
    
    	<complexType name="langString_t">
		<simpleContent>
			<extension base="string">
				<attribute name="lang" type="string" />
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="langStrings_t">
		<sequence>
			<element name="langString" type="aas:langString_t" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>


	<complexType name="embeddedDataSpecification_t">
		<sequence>
			<element name="hasDataSpecification"
				type="aas:reference_t" maxOccurs="1" minOccurs="0">
			</element>
			<element name="dataSpecificationContent"
				type="aas:dataSpecificationContent_t" maxOccurs="1"
				minOccurs="0">
			</element>
		</sequence>
	</complexType>

    

    <complexType name="prvalueType_t"></complexType>

    <complexType name="propertyValueType_t">
    	<simpleContent>
    		<extension base="string"></extension>
    	</simpleContent>
    </complexType>
</schema>

=== admin-shell-io/aasx-package-explorer/src/AasxCsharpLibrary.Tests/TestResources/XmlValidation/expectedInvalidAccordingToSchema/ValidAASMinimum_noId.xml
<?xml version="1.0"?>
<aas:aasenv xmlns:IEC="http://www.admin-shell.io/IEC61360/2/0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:abac="http://www.admin-shell.io/aas/abac/2/0" xsi:schemaLocation="http://www.admin-shell.io/aas/2/0 AAS.xsd http://www.admin-shell.io/IEC61360/2/0 IEC61360.xsd" xmlns:aas="http://www.admin-shell.io/aas/2/0">
  <aas:assetAdministrationShells>
    <aas:assetAdministrationShell>
      <aas:idShort>myAAS</aas:idShort>
      <aas:assetRef>
        <aas:keys>
          <aas:key type="Asset" local="true" idType="">http://example.com/KLIYLHKLYUI</aas:key>
        </aas:keys>
      </aas:assetRef>
      <aas:submodelRefs />
      <aas:conceptDictionaries />
    </aas:assetAdministrationShell>
  </aas:assetAdministrationShells>
  <aas:assets>
    <aas:asset>
      <aas:idShort>myAsset</aas:idShort>
      <aas:identification idType="IRI">http://example.com/KLIYLHKLYUI</aas:identification>
      <aas:kind>Instance</aas:kind>
    </aas:asset>
  </aas:assets>
  <aas:submodels />
  <aas:conceptDescriptions />
</aas:aasenv>

=== admin-shell-io/aasx-package-explorer/src/AasxToolkit/schemaV10/SimpleDrehzahl.xml
<?xml version="1.0" encoding="UTF-8"?>
<aas:aasenv xmlns:aas="http://www.admin-shell.io/aas/1/0" xmlns:aas_common="http://www.admin-shell.io/aas_common/1/0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:IEC="http://www.admin-shell.io/IEC61360/1/0" xsi:schemaLocation="http://www.admin-shell.io/aas/1/0 AAS.xsd http://www.admin-shell.io/IEC61360/1/0 IEC61360.xsd ">
	<aas:assetAdministrationShells>
		<aas:assetAdministrationShell>
			<aas:identification idType="URI">www.admin-shell.io/aas-sample/1/0</aas:identification>
			<aas:administration>
				<aas:version>1</aas:version>
				<aas:revision>0</aas:revision>
			</aas:administration>
			<aas:assetRef>
				<aas:keys>
					<aas:key type="Asset" local="false" idType="URI">http://pk.festo.com/3s7plfdrs35</aas:key>
				</aas:keys>
			</aas:assetRef>
			<aas:submodelRefs>
				<aas:submodelRef>
					<aas:keys>
						<aas:key type="Submodel" local="true" idType="URI">"http://www.zvei.de/demo/submodel/12345679"</aas:key>
					</aas:keys>
				</aas:submodelRef>
			</aas:submodelRefs>
			<aas:views>
				<aas:view>
					<aas:idShort>SampleView</aas:idShort>
					<aas:containedElements>
						<aas:containedElementRef>
							<aas:keys>
								<aas:key type="Submodel" local="true" idType="URI">"http://www.zvei.de/demo/submodel/12345679"</aas:key>
								<aas:key type="Property" local="true" idType="idShort">rotationSpeed</aas:key>
							</aas:keys>
						</aas:containedElementRef>
					</aas:containedElements>
				</aas:view></aas:views>
			<aas:conceptDictionaries>
				<aas:conceptDictionary>
					<aas:idShort>SampleDic</aas:idShort>
					<aas:conceptDescriptionRefs>
					<aas:conceptDescriptionRef>
					<aas:keys>
						<aas:key type="ConceptDescription" local="true" idType="URI">www.festo.com/dic/08111234</aas:key>
					</aas:keys>
					</aas:conceptDescriptionRef>
					<aas:conceptDescriptionRef>
						<aas:keys>
							<aas:key type="ConceptDescription" local="true" idType="IRDI">0173-1#02-BAA120#007</aas:key>
						</aas:keys>
					</aas:conceptDescriptionRef>
					</aas:conceptDescriptionRefs>
					</aas:conceptDictionary>
			</aas:conceptDictionaries>
		</aas:assetAdministrationShell>
	</aas:assetAdministrationShells>
	<aas:assets>
		<aas:asset>
			<aas:idShort>3s7plfdrs35</aas:idShort>
			<aas:description>
				<aas:langString lang="EN">Festo Controller</aas:langString>
			</aas:description>
			<aas:identification idType="URI">http://pk.festo.com/3s7plfdrs35</aas:identification>
			<aas:kind>Instance</aas:kind>
		</aas:asset>
	</aas:assets>
	<aas:submodels>
		<aas:submodel>
			<aas:idShort>Hallo</aas:idShort>
			<aas:identification idType="URI">http://www.zvei.de/demo/submodel/12345679</aas:identification>
			<aas:semanticId >
				<aas:keys>
					<aas:key idType="URI" local="false" type="Submodel">http://www.zvei.de/demo/submodelDefinitions/87654346</aas:key>
				</aas:keys>
			</aas:semanticId>
			<aas:kind>Instance</aas:kind>
			<aas:submodelElements>
				<aas:submodelElement>
					<aas:property>
						<aas:idShort>rotationSpeed</aas:idShort>
						<aas:category>VARIABLE</aas:category>
						<aas:semanticId>
							<aas:keys>
								<aas:key idType="URI" type="ConceptDescription" local="true">www.festo.com/dic/08111234</aas:key>
							</aas:keys>
						</aas:semanticId>
						<aas:valueType>double</aas:valueType>
					</aas:property>
				</aas:submodelElement>
				<aas:submodelElement>
					<aas:property>
						<aas:idShort>NMAX</aas:idShort>
						<aas:category>PARAMETER</aas:category>
						<aas:semanticId>
							<aas:keys>
								<aas:key idType="IRDI" type="GlobalReference" local="true">0173-1#02-BAA120#007</aas:key>
							</aas:keys>
						</aas:semanticId>
						<aas:valueType>double</aas:valueType>
						<aas:value>2000</aas:value>
					</aas:property>
				</aas:submodelElement>
			</aas:submodelElements>
		</aas:submodel>
	</aas:submodels>
	<aas:conceptDescriptions>
		<aas:conceptDescription>
			<aas:identification idType="URI">www.festo.com/dic/08111234</aas:identification>		
			<aas:embeddedDataSpecification>
				<aas:hasDataSpecification>
						<aas:keys>
							<aas:key idType="URI" local="false" type="GlobalReference">www.admin-shell.io/DataSpecificationTemplates/DataSpecificationIEC61360</aas:key>
						</aas:keys>
				</aas:hasDataSpecification>
				<aas:dataSpecificationContent>
					<aas:dataSpecificationIEC61360>
							<IEC:preferredName>
								<aas:langString lang="DE">Drehzahl</aas:langString>
								<aas:langString lang="EN">Rotation Speed</aas:langString>				
							</IEC:preferredName>
							<IEC:shortName>N</IEC:shortName>
							<IEC:unitId>
								<aas:keys>
									<aas:key local="false" type="GlobalReference" idType="IRDI">0173-1#05-AAA650#002</aas:key>
								</aas:keys>
							</IEC:unitId>						
							<IEC:valueFormat>NR1..5</IEC:valueFormat>
					</aas:dataSpecificationIEC61360>
				</aas:dataSpecificationContent>
			</aas:embeddedDataSpecification>
		</aas:conceptDescription>
		<aas:conceptDescription>
			<aas:identification idType="IRDI">0173-1#02-BAA120#007</aas:identification>
			<aas:embeddedDataSpecification>
					<aas:hasDataSpecification>
						<aas:keys>
							<aas:key idType="URI" type="GlobalReference" local="false">www.admin-shell.io/DataSpecificationTemplates/DataSpecificationIEC61360</aas:key>
						</aas:keys>
				   </aas:hasDataSpecification>
			       <aas:dataSpecificationContent>
			         <aas:dataSpecificationIEC61360>
			        	<IEC:preferredName>
			        		<aas:langString lang="DE">maximale Drehzahl</aas:langString>
			        		<aas:langString lang="EN">max rotation speed</aas:langString>
			        	</IEC:preferredName> 
				         <IEC:shortName>NMax</IEC:shortName>
				         <IEC:unitId>
				         	<aas:keys>
				         		<aas:key type="GlobalReference" idType="IRDI" local="false">0173-1#05-AAA650#002</aas:key>
				         	</aas:keys>
				         </IEC:unitId>
				         <IEC:valueFormat>NR1..5</IEC:valueFormat>
			         </aas:dataSpecificationIEC61360>
			       </aas:dataSpecificationContent>
			</aas:embeddedDataSpecification>
		</aas:conceptDescription>
	    <aas:conceptDescription>
	    	<aas:identification idType="URI">"http://smart.festo.com/id/instance/0815"</aas:identification>
	    	<aas:embeddedDataSpecification>
	    		<aas:hasDataSpecification>
	    			<aas:keys>
	    				<aas:key type="GlobalReference" local="false" idType="URI">"www.admin-shell.io/DataSpecificationTemplates/DataSpecificationIEC61360"</aas:key>
	    			</aas:keys>
	    		</aas:hasDataSpecification>
	    		<aas:dataSpecificationContent>
	    			<aas:dataSpecificationIEC61360>
	    				<IEC:preferredName>
	    					<aas:langString lang="DE">Enthaltene CAD Datei"</aas:langString>
	    					<aas:langString lang="EN">"Embedded CAD File" </aas:langString>
	    				</IEC:preferredName>
	    				<IEC:shortName>File</IEC:shortName>
	    				<IEC:unit></IEC:unit>
	    				<IEC:sourceOfDefinition></IEC:sourceOfDefinition>
	    				<IEC:dataType></IEC:dataType>
	    				<IEC:definition>
	    					<aas:langString lang="DE">"Verweis auf enthaltene CAD Datei"</aas:langString>
	    					<aas:langString lang="EN">"Reference to embedded CAD file"</aas:langString>
	    				</IEC:definition>
	    			</aas:dataSpecificationIEC61360>
	    		</aas:dataSpecificationContent>
	    	</aas:embeddedDataSpecification>
	    
	    </aas:conceptDescription>
	</aas:conceptDescriptions>
</aas:aasenv>
